### PR TITLE
Pattern marker generator

### PR DESCRIPTION
**Pull request by le0m**
Implemented pattern marker generator from https://github.com/jeromeetienne/AR.js/blob/master/three.js/examples/marker-training/threex-arpatternfile.js

ref: #2

### CODE REVIEW

**Comment by nicolocarpignoli** [comment]
I will add some test tomorrow. From a review POV it seems ok to me!

**Comment by nicolocarpignoli** [comment]
@le0m Before adding tests, It's better to add a missing piece.

https://github.com/jeromeetienne/AR.js/blob/master/three.js/examples/marker-training/examples/generator.html

If you looking at the current generator, it returns two file:

* a `.patt` file, so the pattern that I think you implemented with the `toPattern` method
* a `.png` file, that is the marker image (the one to print or to show for the tracking): this is the input image plus the configurations from the user - none at the moment - and the black squared border.

After adding that we can also add tests and it will ok for now!

**Comment by le0m** [comment]
Done!

I added a method that takes a Data URI image and outputs the full marker as Data URI.

**Comment by nicolocarpignoli** [comment]
Looks ok to me! I would not waste effort on adding test, we will test this one when implementing the studio side.
Also, we should not forget that NFT (image target) recognisation is coming on AR.js, so possibly markers will be a low-priority stuff (after NFT and Location Based).
For now, this is good!

Thank you @le0m !

**Pull request merged**
